// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfkkgoqvgpsjixbmcunv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBma2tnb3F2Z3Bzaml4Ym1jdW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDg1MTgsImV4cCI6MjA3MjEyNDUxOH0.ADYk_WL5-uvIpTJ23iRU0JbTh3YH7KqcCXtYTvL27_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});